version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:13
    container_name: hotel-pricing-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hotel_pricing
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - hotel-pricing-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: hotel-pricing-api
    depends_on:
      - postgres
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hotel_pricing
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - hotel-pricing-network

  # Frontend Web App
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: hotel-pricing-web
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - hotel-pricing-network

networks:
  hotel-pricing-network:
    driver: bridge

volumes:
  postgres_data:
